# Generated by Django 4.1.2 on 2022-10-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Öğrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim_soyisim', models.CharField(max_length=25, verbose_name='isim, soyisim')),
                ('sınıf', models.CharField(max_length=15, verbose_name='sınıf')),
                ('açıklama', models.TextField(max_length=250, verbose_name='açıklama')),
            ],
        ),
        migrations.CreateModel(
            name='Öğretmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim_soyisim', models.CharField(max_length=25, verbose_name='isim, soyisim')),
                ('branş', models.CharField(max_length=25, verbose_name='branş')),
                ('tel', models.CharField(max_length=11, verbose_name='No')),
            ],
        ),
        migrations.CreateModel(
            name='ÖzelDers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_ad', models.CharField(max_length=25, verbose_name='Dersin adı')),
                ('ders_konu', models.CharField(max_length=50, verbose_name='Ders konu')),
                ('ders_tarihi', models.DateField()),
                ('ders_saati', models.TimeField()),
                ('ders_yeri', models.CharField(max_length=100, verbose_name='Ders yeri')),
                ('öğrenci', models.ManyToManyField(max_length=25, related_name='Öğrenci', to='özelders.öğrenci')),
                ('öğretmen', models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, to='özelders.öğretmen')),
            ],
        ),
    ]
