# Generated by Django 4.1.2 on 2022-10-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('özelders', '0006_alter_özelders_fiyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='özelders',
            name='fiyat',
            field=models.IntegerField(default='dasşmdasd', verbose_name='Ders ücreti'),
        ),
        migrations.AlterField(
            model_name='öğrenci',
            name='açıklama',
            field=models.TextField(default='Öğrenci', max_length=250, verbose_name='Açıklama'),
        ),
    ]
