# Generated by Django 4.1.2 on 2022-11-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('özelders', '0007_alter_özelders_fiyat_alter_öğrenci_açıklama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ucretler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('öğr_isim', models.CharField(max_length=25, verbose_name='öğrenci isim')),
                ('ders_tarihi', models.DateField()),
                ('ders_saati', models.TimeField()),
                ('ucret', models.IntegerField(default=250, verbose_name='Ders ücreti')),
            ],
        ),
        migrations.RemoveField(
            model_name='öğrenci',
            name='açıklama',
        ),
        migrations.AlterField(
            model_name='özelders',
            name='fiyat',
            field=models.IntegerField(default=250, verbose_name='Ders ücreti'),
        ),
    ]
