# Generated by Django 4.1.2 on 2022-11-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('özelders', '0008_ucretler_remove_öğrenci_açıklama_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ucretler',
            name='ders_saati',
        ),
        migrations.RemoveField(
            model_name='ucretler',
            name='ders_tarihi',
        ),
        migrations.RemoveField(
            model_name='ucretler',
            name='ucret',
        ),
        migrations.RemoveField(
            model_name='ucretler',
            name='öğr_isim',
        ),
    ]
