# Generated by Django 4.1.2 on 2022-11-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('özelders', '0009_remove_ucretler_ders_saati_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='özelders',
            name='ders_saati',
            field=models.CharField(max_length=5),
        ),
    ]
