# Generated by Django 4.1.2 on 2022-11-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('özelders', '0010_alter_özelders_ders_saati'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucretler',
            name='isim',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
