# Generated by Django 4.1.2 on 2022-11-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('özelders', '0011_ucretler_isim'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucretler',
            name='ders_saati',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ucretler',
            name='ders_tarihi',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ucretler',
            name='fiyat',
            field=models.IntegerField(default=250, null=True, verbose_name='Ders ücreti'),
        ),
    ]
