# Generated by Django 4.1.2 on 2022-11-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('özelders', '0014_öğrenci_bölüm_öğrenci_sınıf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='öğrenci',
            name='bölüm',
            field=models.CharField(max_length=3, verbose_name='Bölüm (EA,SAY,DİL)'),
        ),
        migrations.AlterField(
            model_name='öğrenci',
            name='sınıf',
            field=models.CharField(max_length=2, verbose_name='Sınıf'),
        ),
    ]
