# Generated by Django 4.1.2 on 2022-11-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('özelders', '0015_alter_öğrenci_bölüm_alter_öğrenci_sınıf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='öğrenci',
            name='bölüm',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Bölüm (EA,SAY,DİL)'),
        ),
        migrations.AlterField(
            model_name='öğrenci',
            name='sınıf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Sınıf'),
        ),
    ]
