# Generated by Django 4.1.2 on 2022-11-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('özelders', '0016_alter_öğrenci_bölüm_alter_öğrenci_sınıf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='öğrenci',
            name='bölüm',
        ),
        migrations.RemoveField(
            model_name='öğrenci',
            name='sınıf',
        ),
    ]
